name: Publish

on:
  push:
    tags: [ release-* ]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
        node-version: [18]
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: src/SqlAccountRestAPI/wwwroot/dashboard
      - run: npm run build
        working-directory: src/SqlAccountRestAPI/wwwroot/dashboard

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="sql-accounting-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish src/SqlAccountRestAPI/SqlAccountRestAPI.csproj --runtime "${{ matrix.target }}" -c Release -o "$release_name"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "sql-account-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}